// Copyright 2026 anti-cheat-scorecard Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0

// Package generatedprojectionclaimsauthority detects generated projections
// that assert standing/certification authority instead of remaining consequence-only.
package generatedprojectionclaimsauthority

import (
	"regexp"
	"strings"

	"github.com/ossf/scorecard/v5/internal/llmcheat"
)

const (
	patternID = "generated-projection-claims-authority"
	category  = "governed-execution-integrity"
)

var (
	generatedRe = regexp.MustCompile(`(?i)(code generated|generated file|generated by|do not edit|manufactured projection)`)
	authorityRe = regexp.MustCompile(`(?i)\b(authoritative|standing authority|certif(?:y|ies|ied)|grants? authority|declares? ALIVE|status\s*[:=]\s*["']?ALIVE)\b`)
	negationRe  = regexp.MustCompile(`(?i)\b(zero|no|without|cannot|may not|must not)\b.{0,20}\b(authority|certif|ALIVE)\b`)
)

type detector struct{}

func (d *detector) ID() string       { return patternID }
func (d *detector) Category() string { return category }
func (d *detector) Detect(path string, content []byte) []llmcheat.Match {
	text := string(content)
	generatedLoc := generatedRe.FindStringIndex(text)
	if generatedLoc == nil && !strings.Contains(strings.ToLower(filepathSlash(path)), "/generated/") {
		return nil
	}
	authorityLoc := authorityRe.FindStringIndex(text)
	if authorityLoc == nil || negationRe.MatchString(text) {
		return nil
	}
	line := uint(1 + strings.Count(text[:authorityLoc[0]], "\n"))
	return []llmcheat.Match{{PatternID: patternID, Category: category, Path: path, Line: line,
		Message:  "generated projection claims certification/standing authority; generated outputs are consequences and must not be their own authority source",
		Severity: llmcheat.SeverityHigh}}
}
func filepathSlash(path string) string { return strings.ReplaceAll(path, "\\", "/") }

//nolint:gochecknoinits // package registration is the production plugin contract.
func init() { llmcheat.Register(&detector{}) }
