// Copyright 2026 anti-cheat-scorecard Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0

package generatedprojectionclaimsauthority

import "testing"

func TestDetect(t *testing.T) {
	t.Parallel()
	d := &detector{}
	tests := []struct {
		name, path, body string
		want             int
	}{
		{"generated authority", "generated/court.yml", "# Code generated by ggen. DO NOT EDIT.\nstatus: ALIVE\n", 1},
		{"explicit zero authority", "generated/court.yml", "# Code generated by ggen.\nThis projection has zero standing authority.\n", 0},
		{"authored", "court.yml", "status: ALIVE\n", 0},
	}
	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			if got := len(d.Detect(tc.path, []byte(tc.body))); got != tc.want {
				t.Fatalf("got %d want %d", got, tc.want)
			}
		})
	}
}
