// Copyright 2026 anti-cheat-scorecard Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package handeditedgeneratedfilemarker

import (
	"strings"
	"testing"

	"github.com/ossf/scorecard/v5/internal/llmcheat"
)

// dirtyGoSource is a realistic generated Go protobuf file whose header
// declares it must never be edited, and whose body was hand-patched anyway.
const dirtyGoSource = `// Code generated by protoc-gen-go. DO NOT EDIT.
// source: widget.proto

package pb

import (
	"google.golang.org/protobuf/proto"
)

// Widget is a generated protobuf message type.
type Widget struct {
	Id   string
	Name string
}

// Reset implements proto.Message.
func (w *Widget) Reset() {
	// HACK: patched this line by hand, remove after regen
	*w = Widget{}
}

func (w *Widget) String() string {
	return proto.CompactTextString(w)
}
`

// cleanGoSource is a realistic generated Go protobuf file whose header
// declares it generated and whose body contains only real generated code —
// no editorial markers anywhere.
const cleanGoSource = `// Code generated by protoc-gen-go. DO NOT EDIT.
// source: widget.proto

package pb

import (
	"google.golang.org/protobuf/proto"
)

// Widget is a generated protobuf message type.
type Widget struct {
	Id   string
	Name string
}

// Reset implements proto.Message.
func (w *Widget) Reset() {
	*w = Widget{}
}

func (w *Widget) String() string {
	return proto.CompactTextString(w)
}
`

func TestDetect_DirtyGeneratedFileWithHackComment_ProducesMatch(t *testing.T) {
	d := detector{}

	matches := d.Detect("pb/widget.pb.go", []byte(dirtyGoSource))

	if len(matches) < 1 {
		t.Fatalf("Detect() on dirty fixture = %d matches, want >= 1", len(matches))
	}

	got := matches[0]
	if got.PatternID != patternID {
		t.Errorf("Match.PatternID = %q, want %q", got.PatternID, patternID)
	}
	if got.Category != patternCategory {
		t.Errorf("Match.Category = %q, want %q", got.Category, patternCategory)
	}
	if got.Path != "pb/widget.pb.go" {
		t.Errorf("Match.Path = %q, want %q", got.Path, "pb/widget.pb.go")
	}

	// Derive the expected 1-based line number directly from the fixture
	// text itself (rather than a hand-counted literal, which is easy to get
	// off-by-one on a multi-line raw string) so the assertion stays correct
	// even if the fixture is edited later.
	wantLine := uint(0)
	for i, line := range strings.Split(dirtyGoSource, "\n") {
		if strings.Contains(line, "// HACK") {
			wantLine = uint(i + 1)
			break
		}
	}
	if wantLine == 0 {
		t.Fatal("test fixture bug: dirtyGoSource does not contain the expected // HACK marker")
	}
	if got.Line != wantLine {
		t.Errorf("Match.Line = %d, want %d", got.Line, wantLine)
	}
	if got.Severity != llmcheat.SeverityHigh {
		t.Errorf("Match.Severity = %q, want %q", got.Severity, llmcheat.SeverityHigh)
	}
	if got.Message == "" {
		t.Error("Match.Message is empty, want a real explanation")
	}
}

func TestDetect_CleanGeneratedFile_ProducesNoMatches(t *testing.T) {
	d := detector{}

	matches := d.Detect("pb/widget.pb.go", []byte(cleanGoSource))

	if len(matches) != 0 {
		t.Fatalf("Detect() on clean fixture = %d matches, want 0; matches=%+v", len(matches), matches)
	}
}

// TestDetect_EditorialMarkerWithoutGeneratedHeader_ProducesNoMatches proves
// the combination requirement: an ordinary, non-generated source file that
// happens to contain a "// HACK" comment (a completely legitimate thing for
// a human-authored file to say) must not be flagged. The generated-marker
// header is the other half of the signal, and it is absent here.
func TestDetect_EditorialMarkerWithoutGeneratedHeader_ProducesNoMatches(t *testing.T) {
	const src = `package store

// Save persists record to the backing store.
func Save(record []byte) error {
	// HACK: batching writes here until the real queue lands
	return flush(record)
}
`
	d := detector{}

	matches := d.Detect("store/save.go", []byte(src))

	if len(matches) != 0 {
		t.Fatalf("Detect() on non-generated fixture = %d matches, want 0; matches=%+v", len(matches), matches)
	}
}

// TestDetect_GeneratedMarkerOutsideHeaderWindow_ProducesNoMatches proves the
// maxHeaderLines boundary: a "DO NOT EDIT" marker that appears after the
// first 5 lines (pushed down by a long license preamble) does not count as
// a generated-file declaration, even though the file also contains an
// editorial marker later on.
func TestDetect_GeneratedMarkerOutsideHeaderWindow_ProducesNoMatches(t *testing.T) {
	const src = `// Copyright 2026 Example Corp.
// Licensed under the Apache License, Version 2.0.
// See LICENSE for details.
// Contact: legal@example.com
// Repository: github.com/example/widgets
// Code generated by protoc-gen-go. DO NOT EDIT.

package pb

// HACK: patched this line by hand, remove after regen
type Widget struct{}
`
	d := detector{}

	matches := d.Detect("pb/widget.pb.go", []byte(src))

	if len(matches) != 0 {
		t.Fatalf("Detect() with marker outside header window = %d matches, want 0; matches=%+v", len(matches), matches)
	}
}

// TestDetect_AtGeneratedMarkerAndPythonManualFix_ProducesMatch proves two
// other stated variants together: the "@generated" marker style (as used by
// Facebook/Meta-style tooling) and the "# manual fix" Python-comment
// editorial marker, in a non-Go file, to confirm this pattern is not
// accidentally scoped to only Go/protobuf files.
func TestDetect_AtGeneratedMarkerAndPythonManualFix_ProducesMatch(t *testing.T) {
	const src = `#!/usr/bin/env python3
# @generated by codegen.py
# Do not modify this file directly.

def compute_checksum(data):
    # original generated body computed a naive sum here
    total = 0
    # manual fix: switched to CRC32 because the naive sum collided in prod
    return crc32(data)
`
	d := detector{}

	matches := d.Detect("gen/checksum.py", []byte(src))

	if len(matches) != 1 {
		t.Fatalf("Detect() on @generated/python fixture = %d matches, want 1; matches=%+v", len(matches), matches)
	}
	got := matches[0]
	if got.PatternID != patternID {
		t.Errorf("Match.PatternID = %q, want %q", got.PatternID, patternID)
	}
	if got.Category != patternCategory {
		t.Errorf("Match.Category = %q, want %q", got.Category, patternCategory)
	}
	wantLine := uint(0)
	for i, line := range strings.Split(src, "\n") {
		if strings.Contains(line, "# manual fix") {
			wantLine = uint(i + 1)
			break
		}
	}
	if got.Line != wantLine {
		t.Errorf("Match.Line = %d, want %d", got.Line, wantLine)
	}
}

// TestDetect_MultipleEditorialMarkers_ProducesOneMatchPerLine proves that
// every distinct editorial-marker line in a hand-edited generated file is
// reported, not just the first one found — here two different marker
// spellings ("// HACK" and "// hand-edited") in the same generated file.
func TestDetect_MultipleEditorialMarkers_ProducesOneMatchPerLine(t *testing.T) {
	const src = `// Code generated by mockgen. DO NOT EDIT.
package mocks

// NewClient returns a generated mock client.
func NewClient() *Client {
	// HACK: forcing a non-nil default here, remove after regen
	c := &Client{}
	// hand-edited: bumped retry count for the flaky CI run
	c.Retries = 5
	return c
}
`
	d := detector{}

	matches := d.Detect("gen/mocks.go", []byte(src))

	if len(matches) != 2 {
		t.Fatalf("Detect() on multi-marker fixture = %d matches, want 2; matches=%+v", len(matches), matches)
	}
	if matches[0].Line != 6 {
		t.Errorf("matches[0].Line = %d, want 6", matches[0].Line)
	}
	if matches[1].Line != 8 {
		t.Errorf("matches[1].Line = %d, want 8", matches[1].Line)
	}
	for _, m := range matches {
		if m.PatternID != patternID {
			t.Errorf("Match.PatternID = %q, want %q", m.PatternID, patternID)
		}
		if m.Category != patternCategory {
			t.Errorf("Match.Category = %q, want %q", m.Category, patternCategory)
		}
	}
}

// TestDetect_EmptyContent_ProducesNoMatches guards the zero-value input
// edge case: empty file content must never panic or fabricate a match.
func TestDetect_EmptyContent_ProducesNoMatches(t *testing.T) {
	d := detector{}

	matches := d.Detect("empty.go", []byte(""))

	if len(matches) != 0 {
		t.Fatalf("Detect() on empty content = %d matches, want 0; matches=%+v", len(matches), matches)
	}
}

func TestPattern_IDAndCategory(t *testing.T) {
	d := detector{}

	if got := d.ID(); got != patternID {
		t.Errorf("ID() = %q, want %q", got, patternID)
	}
	if got := d.Category(); got != patternCategory {
		t.Errorf("Category() = %q, want %q", got, patternCategory)
	}
	if got := d.ID(); got != "hand-edited-generated-file-marker" {
		t.Errorf("ID() = %q, want the literal spec ID %q", got, "hand-edited-generated-file-marker")
	}
	if got := d.Category(); got != "generated-artifact-tampering" {
		t.Errorf("Category() = %q, want the literal spec Category %q", got, "generated-artifact-tampering")
	}
}
