// Copyright 2026 anti-cheat-scorecard Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package lockfilehandeditedwithouttoolrun

import (
	"testing"

	"github.com/ossf/scorecard/v5/internal/llmcheat"
)

// TestDetect_DirtyHandEditedCargoLock proves a realistic Cargo.lock with a
// clean two-line generator header AND one hand-authored mid-file comment
// ("regenerated by hand ... do not overwrite") produces exactly one match,
// pinned to the exact hand-edited line, with the correct PatternID and
// Category.
func TestDetect_DirtyHandEditedCargoLock(t *testing.T) {
	const src = `# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 3

[[package]]
name = "anyhow"
version = "1.0.75"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "a4668cab20f66d8d020e1fbc0ebe47217433c1b6c8f2040ff0f6d10a3162447"

# regenerated by hand because ggen sync failed, do not overwrite
[[package]]
name = "autocfg"
version = "1.1.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "d468802bab17cbc0cc575e9b053f41e72aa36bfa6b7f55e3529576d20a95267"
`
	d := detector{}
	got := d.Detect("Cargo.lock", []byte(src))

	if len(got) != 1 {
		t.Fatalf("Detect() returned %d matches, want exactly 1 (the mid-file hand-edit comment); got %+v", len(got), got)
	}

	m := got[0]
	if m.PatternID != "lockfile-hand-edited-without-tool-run" {
		t.Errorf("match PatternID = %q, want %q", m.PatternID, "lockfile-hand-edited-without-tool-run")
	}
	if m.Category != "generated-artifact-tampering" {
		t.Errorf("match Category = %q, want %q", m.Category, "generated-artifact-tampering")
	}
	if m.Path != "Cargo.lock" {
		t.Errorf("match Path = %q, want %q", m.Path, "Cargo.lock")
	}
	// Line 11 is "# regenerated by hand because ggen sync failed, do not
	// overwrite" (1-based, counting the leading "# This file is
	// automatically @generated by Cargo." as line 1).
	if m.Line != 11 {
		t.Errorf("match Line = %d, want 11", m.Line)
	}
}

// TestDetect_DirtySingleLineExample proves the exact single-line dirty
// example from the pattern's own spec ("# regenerated by hand because ggen
// sync failed, do not overwrite" immediately followed by "[[package]]")
// produces at least one match even with no other content in the file —
// this is the literal minimal case, distinct from the fuller realistic
// fixture above.
func TestDetect_DirtySingleLineExample(t *testing.T) {
	const src = "# regenerated by hand because ggen sync failed, do not overwrite\n[[package]]\n"

	d := detector{}
	got := d.Detect("Cargo.lock", []byte(src))

	if len(got) < 1 {
		t.Fatalf("Detect() returned %d matches, want at least 1 for the spec's dirty example", len(got))
	}
	if got[0].PatternID != "lockfile-hand-edited-without-tool-run" {
		t.Errorf("match PatternID = %q, want %q", got[0].PatternID, "lockfile-hand-edited-without-tool-run")
	}
	if got[0].Category != "generated-artifact-tampering" {
		t.Errorf("match Category = %q, want %q", got[0].Category, "generated-artifact-tampering")
	}
}

// TestDetect_CleanGeneratedCargoLock proves the exact clean example from the
// pattern's own spec (a two-line "@generated"/"not intended for manual
// editing" header, nothing else) produces zero matches.
func TestDetect_CleanGeneratedCargoLock(t *testing.T) {
	const src = "# This file is automatically @generated by Cargo.\n" +
		"# It is not intended for manual editing.\n" +
		"[[package]]\n"

	d := detector{}
	got := d.Detect("Cargo.lock", []byte(src))

	if len(got) != 0 {
		t.Fatalf("Detect() returned %d matches, want 0 for the spec's clean example; got %+v", len(got), got)
	}
}

// TestDetect_CleanYarnStyleHeader proves a realistic multi-line generator
// header that spans two DIFFERENT recognized disclaimer phrases (a
// "DO NOT EDIT" line followed by a short "lockfile vN" version tag line, as
// real yarn.lock files ship) is not flagged just because the second header
// line does not itself repeat a "generated" phrase.
func TestDetect_CleanYarnStyleHeader(t *testing.T) {
	const src = `# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


"@babel/core@^7.0.0":
  version "7.22.0"
  resolved "https://registry.yarnpkg.com/@babel/core/-/core-7.22.0.tgz"
`
	d := detector{}
	got := d.Detect("yarn.lock", []byte(src))

	if len(got) != 0 {
		t.Fatalf("Detect() returned %d matches, want 0 for a genuine yarn.lock header; got %+v", len(got), got)
	}
}

// TestDetect_CleanPackageLockJSON proves a real package-lock.json (pure
// JSON, no comment lines at all) produces zero matches, including exercise
// of the exact-filename match path (package-lock.json does not end in
// ".lock").
func TestDetect_CleanPackageLockJSON(t *testing.T) {
	const src = `{
  "name": "example",
  "version": "1.0.0",
  "lockfileVersion": 3,
  "packages": {
    "": {
      "name": "example",
      "version": "1.0.0"
    }
  }
}
`
	d := detector{}
	got := d.Detect("package-lock.json", []byte(src))

	if len(got) != 0 {
		t.Fatalf("Detect() returned %d matches, want 0 for a clean package-lock.json; got %+v", len(got), got)
	}
}

// TestDetect_DirtyPoetryLockAndLockToml proves the detector covers the
// other named filenames/suffixes from the spec (poetry.lock and a generic
// *.lock.toml file), each with a hand-authored mid-file comment.
func TestDetect_DirtyPoetryLockAndLockToml(t *testing.T) {
	const src = `# This file is automatically @generated by Poetry and should not be changed by hand.

[[package]]
name = "requests"
version = "2.31.0"

# had to patch this in manually since poetry lock kept timing out on CI
[[package]]
name = "urllib3"
version = "2.0.4"
`

	cases := []struct {
		name string
		path string
	}{
		{"poetry.lock exact name", "poetry.lock"},
		{"generic .lock.toml suffix", "deps.lock.toml"},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			d := detector{}
			got := d.Detect(tc.path, []byte(src))
			if len(got) != 1 {
				t.Fatalf("Detect(%q) returned %d matches, want exactly 1; got %+v", tc.path, len(got), got)
			}
			if got[0].Severity != llmcheat.SeverityMedium {
				t.Errorf("match Severity = %q, want %q", got[0].Severity, llmcheat.SeverityMedium)
			}
		})
	}
}

// TestDetect_SlashSlashCommentStyleFlagged proves the "//" comment prefix
// named in the spec (alongside "#") is also honored, not just "#".
func TestDetect_SlashSlashCommentStyleFlagged(t *testing.T) {
	const src = `// autogenerated, do not edit
{
  "name": "widget"
}
// added this dependency manually because npm install kept failing on CI
`
	d := detector{}
	got := d.Detect("custom.lock", []byte(src))

	if len(got) != 1 {
		t.Fatalf("Detect() returned %d matches, want exactly 1; got %+v", len(got), got)
	}
	if got[0].Line != 5 {
		t.Errorf("match Line = %d, want 5", got[0].Line)
	}
}

// TestDetect_PunctuationOnlyDividerNotFlagged proves a comment line with no
// letters at all (a bare divider) is never flagged, per the pattern
// description's explicit "contains letters" qualifier.
func TestDetect_PunctuationOnlyDividerNotFlagged(t *testing.T) {
	const src = `# ------------------------------------------------------------
[[package]]
name = "foo"
`
	d := detector{}
	got := d.Detect("Cargo.lock", []byte(src))

	if len(got) != 0 {
		t.Fatalf("Detect() returned %d matches, want 0 for a punctuation-only divider comment; got %+v", len(got), got)
	}
}

// TestDetect_NonLockfileIgnored proves the detector only inspects files
// whose path matches one of the named lockfile patterns, even when the
// content contains the exact dirty comment text.
func TestDetect_NonLockfileIgnored(t *testing.T) {
	const src = "# regenerated by hand because ggen sync failed, do not overwrite\n[[package]]\n"

	d := detector{}
	got := d.Detect("notes.md", []byte(src))

	if len(got) != 0 {
		t.Fatalf("Detect() returned %d matches for a non-lockfile path, want 0; got %+v", len(got), got)
	}

	// Sanity check: the identical content at a real lockfile path IS
	// flagged, so the zero-match result above is really the path filter at
	// work and not some other bug silently swallowing the match.
	got2 := d.Detect("Cargo.lock", []byte(src))
	if len(got2) < 1 {
		t.Fatalf("Detect() returned %d matches for the equivalent Cargo.lock path, want at least 1", len(got2))
	}
}

// TestID_Category proves the detector reports the exact ID/Category
// contract this pattern was assigned.
func TestID_Category(t *testing.T) {
	d := detector{}
	if got := d.ID(); got != "lockfile-hand-edited-without-tool-run" {
		t.Errorf("ID() = %q, want %q", got, "lockfile-hand-edited-without-tool-run")
	}
	if got := d.Category(); got != "generated-artifact-tampering" {
		t.Errorf("Category() = %q, want %q", got, "generated-artifact-tampering")
	}
}
