// Copyright 2026 anti-cheat-scorecard Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Package lockfilehandeditedwithouttoolrun detects lockfiles (Cargo.lock,
// package-lock.json, poetry.lock, Gemfile.lock, and any generic *.lock or
// *.lock.toml file) that carry a free-form, human-authored comment line.
//
// Real lockfiles produced by real tooling are machine-only apart from a
// short, fixed boilerplate header ("This file is automatically @generated
// by Cargo.", "DO NOT EDIT THIS FILE DIRECTLY.", "yarn lockfile v1", and the
// like) — the tool that owns the file never emits free-form prose into it.
// A comment line that does not match one of those recognized generator
// disclaimers is therefore a strong signal that a human (or an agent)
// hand-edited the lockfile directly instead of re-running the real
// dependency tool, exactly the kind of "regenerated by hand because the
// real tool run failed" shortcut this detector exists to catch.
//
// The classifier is content-based, not line-position-based: a lockfile's
// real generator header is very often more than one line (Cargo.lock ships
// two), so "only line 1 is exempt" both under- and over-flags in practice —
// it would wrongly flag a legitimate second header line, and would wrongly
// exempt a single dishonest comment that happens to be the file's very
// first line. What actually distinguishes a tool header from a hand-edit is
// whether the comment reads as one of the small set of known machine
// disclaimers, not where in the file it sits.
package lockfilehandeditedwithouttoolrun

import (
	"bufio"
	"bytes"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/ossf/scorecard/v5/internal/llmcheat"
)

const (
	patternID = "lockfile-hand-edited-without-tool-run"
	category  = "generated-artifact-tampering"
)

// exactLockfileNames are lockfile filenames matched case-insensitively in
// full, independent of extension-based rules below (package-lock.json in
// particular does not end in ".lock" at all).
var exactLockfileNames = map[string]bool{
	"cargo.lock":        true,
	"package-lock.json": true,
	"poetry.lock":       true,
	"gemfile.lock":      true,
}

// hasLetterRe matches any ASCII or Unicode letter; a comment line with no
// letters at all (a bare divider like "#---------" or "// ==========") is
// never itself readable prose and is never flagged, per the pattern
// description's "contains letters, not just a tool-generated header" test.
var hasLetterRe = regexp.MustCompile(`\p{L}`)

// generatorHeaderRe matches the small, closed set of real generator
// disclaimer phrases seen in real Cargo.lock, package-lock.json (when
// hand-annotated by npm's own tooling), poetry.lock, Gemfile.lock, and
// yarn.lock header comments. Word-boundary anchors (\b) are load-bearing:
// without them, "generated by" would also match inside a hand-written
// sentence like "regenerated by hand", since "generated" is itself a
// substring of "regenerated" — the boundary forces "generated" to be its
// own separate word, which "regenerated" never contains.
var generatorHeaderRe = regexp.MustCompile(`(?i)` +
	`@generated` +
	`|\bauto-?generated\b` +
	`|\bautomatically\s+generated\b` +
	`|\bgenerated\s+by\b` +
	`|\bthis\s+file\s+is\s+generated\b` +
	`|\bmachine[- ]generated\b` +
	`|\bdo\s+not\s+edit\b` +
	`|\bdo\s+not\s+modify\b` +
	`|\bnot\s+intended\s+for\s+manual\s+editing\b` +
	`|\blockfile\s+v\d+\b`)

// isLockfilePath reports whether path names a lockfile this detector should
// inspect: an exact well-known lockfile filename, or a generic *.lock /
// *.lock.toml suffix (case-insensitive, matched on the base filename so a
// directory named e.g. "lock/" does not itself trigger a match).
func isLockfilePath(path string) bool {
	base := strings.ToLower(filepath.Base(path))

	if exactLockfileNames[base] {
		return true
	}
	if strings.HasSuffix(base, ".lock.toml") {
		return true
	}
	if strings.HasSuffix(base, ".lock") {
		return true
	}
	return false
}

// detector is the Pattern implementation for this package. It is
// unexported: callers outside this package only ever interact with it
// through the llmcheat.Pattern interface (or, in tests, by constructing it
// directly).
type detector struct{}

func (detector) ID() string       { return patternID }
func (detector) Category() string { return category }

// Detect scans one lockfile's content line by line and flags every comment
// line ("#" or "//" prefixed, after trimming leading whitespace) that
// contains real letters but does not match a recognized tool-generated
// header disclaimer. It is a pure line scanner: no filesystem access, no
// TOML/JSON parsing, no shared mutable state beyond the one Register call
// in init().
func (detector) Detect(path string, content []byte) []llmcheat.Match {
	if !isLockfilePath(path) {
		return nil
	}

	var matches []llmcheat.Match

	scanner := bufio.NewScanner(bytes.NewReader(content))
	scanner.Buffer(make([]byte, 0, 64*1024), 1024*1024)

	var lineNum uint
	for scanner.Scan() {
		lineNum++
		trimmed := strings.TrimSpace(scanner.Text())

		isComment := strings.HasPrefix(trimmed, "#") || strings.HasPrefix(trimmed, "//")
		if !isComment {
			continue
		}
		if !hasLetterRe.MatchString(trimmed) {
			// A bare divider/punctuation-only comment line carries no prose
			// to judge as human-authored or not.
			continue
		}
		if generatorHeaderRe.MatchString(trimmed) {
			// Matches a known real-tool disclaimer (e.g. "@generated",
			// "do not edit", "yarn lockfile v1") — legitimate machine
			// header text, not a hand-edit signal.
			continue
		}

		matches = append(matches, llmcheat.Match{
			PatternID: patternID,
			Category:  category,
			Path:      path,
			Line:      lineNum,
			Message: "comment in a lockfile does not match any recognized tool-generated header " +
				"phrase (e.g. \"@generated\", \"do not edit\") — real lockfiles from real tools " +
				"are machine-only apart from that boilerplate header, so a free-form comment " +
				"like this is a sign the lockfile was hand-edited instead of regenerated by the " +
				"real dependency tool",
			Severity: llmcheat.SeverityMedium,
		})
	}

	return matches
}

func init() {
	llmcheat.Register(detector{})
}
