// Copyright 2026 anti-cheat-scorecard Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package lockfilechecksummismatch

import (
	"testing"

	"github.com/ossf/scorecard/v5/internal/llmcheat"
)

// Chicago-style throughout: every test constructs the real detector{} type
// directly and calls the real Detect on real, realistic multi-line byte
// content, then asserts on the real returned []llmcheat.Match slice. There
// is no collaborator here to fake -- Detect is a pure function of its two
// arguments -- so there is nothing legitimate to mock.
//
// The hex fixtures below are real sha256/sha1 digests (sha256sum/sha1sum of
// the literal strings "pkg-v1" and "pkg-v2"), chosen only so the two values
// per pair are genuinely 64/40 hex characters and genuinely different --
// not because the preimage matters to the detector, which never hashes
// anything itself.
const (
	sha256A = "c0e513ac279d1b740000c29cd5703994027d85bf355bddcea8c972502840c7e7"
	sha256B = "3646554da874516a8f8996fb6e6f93403daf4dceb300c46bf10c3a9068f56b9e"
	sha1A   = "26020150486c2658b308e3f338c685bbce2c85ab"
	sha1B   = "ff1feb3d6eb7a8f0e36a5eab925b5448c852885e"
)

// TestFixtureHexLengths guards the const fixtures above against a
// transcription typo: if sha256A/B or sha1A/B ever drifted off 64/40 hex
// characters, checksumLineRe would silently stop matching them and every
// other test in this file would go quietly, misleadingly green.
func TestFixtureHexLengths(t *testing.T) {
	for name, v := range map[string]string{"sha256A": sha256A, "sha256B": sha256B} {
		if len(v) != 64 {
			t.Errorf("%s has length %d, want 64", name, len(v))
		}
	}
	for name, v := range map[string]string{"sha1A": sha1A, "sha1B": sha1B} {
		if len(v) != 40 {
			t.Errorf("%s has length %d, want 40", name, len(v))
		}
	}
}

func assertMatch(t *testing.T, m llmcheat.Match, wantLine uint) {
	t.Helper()
	if m.PatternID != patternID {
		t.Errorf("PatternID = %q, want %q", m.PatternID, patternID)
	}
	if m.Category != category {
		t.Errorf("Category = %q, want %q", m.Category, category)
	}
	if m.Line != wantLine {
		t.Errorf("Line = %d, want %d", m.Line, wantLine)
	}
	if m.Message == "" {
		t.Error("Message is empty, want a real explanation")
	}
	if m.Severity != llmcheat.SeverityHigh {
		t.Errorf("Severity = %q, want %q", m.Severity, llmcheat.SeverityHigh)
	}
}

// TestDetect_DirtyTOMLLockfile_ProducesMatch expands the task's one-line
// dirty example into a realistic Cargo.lock-shaped fragment: the same
// package name repeated across two [[package]] entries with two different
// checksum values for what is nominally the same named subject.
func TestDetect_DirtyTOMLLockfile_ProducesMatch(t *testing.T) {
	content := []byte(
		"# This file is automatically @generated by Cargo.\n" +
			"# It is not intended for manual editing.\n" +
			"version = 3\n" +
			"\n" +
			"[[package]]\n" +
			"name = \"pkg\"\n" +
			"version = \"1.0.0\"\n" +
			"checksum = \"" + sha256A + "\"\n" +
			"\n" +
			"[[package]]\n" +
			"name = \"pkg\"\n" +
			"version = \"1.0.0\"\n" +
			"checksum = \"" + sha256B + "\"\n",
	)

	d := detector{}
	matches := d.Detect("Cargo.lock.toml", content)

	if len(matches) != 1 {
		t.Fatalf("Detect() returned %d matches, want exactly 1 for a same-subject checksum mismatch; matches=%+v", len(matches), matches)
	}
	// Line 13 is the second "checksum = ..." line.
	assertMatch(t, matches[0], 13)
}

// TestDetect_CleanTOMLLockfile_ProducesNoMatch expands the task's one-line
// clean example: a single, internally consistent name/checksum pair.
func TestDetect_CleanTOMLLockfile_ProducesNoMatch(t *testing.T) {
	content := []byte(
		"[[package]]\n" +
			"name = \"pkg\"\n" +
			"version = \"1.0.0\"\n" +
			"checksum = \"" + sha256A + "\"\n",
	)

	d := detector{}
	matches := d.Detect("Cargo.lock.toml", content)

	if len(matches) != 0 {
		t.Fatalf("Detect() returned %d matches, want 0 for an internally consistent lockfile; matches=%+v", len(matches), matches)
	}
}

// TestDetect_RepeatedIdenticalChecksum_ProducesNoMatch covers the boundary
// the description implies but doesn't spell out: the same key name
// appearing twice for the same subject is only a contradiction if the
// VALUES differ. Verbatim repetition (a package block duplicated as-is, or
// a checksum re-asserted unchanged) must not be flagged.
func TestDetect_RepeatedIdenticalChecksum_ProducesNoMatch(t *testing.T) {
	content := []byte(
		"[[package]]\n" +
			"name = \"pkg\"\n" +
			"checksum = \"" + sha256A + "\"\n" +
			"\n" +
			"[[package]]\n" +
			"name = \"pkg\"\n" +
			"checksum = \"" + sha256A + "\"\n",
	)

	d := detector{}
	matches := d.Detect("Cargo.lock.toml", content)

	if len(matches) != 0 {
		t.Fatalf("Detect() returned %d matches, want 0 when the repeated checksum value is identical; matches=%+v", len(matches), matches)
	}
}

// TestDetect_SameKeyDifferentSubjects_ProducesNoMatch covers the other
// boundary: two DIFFERENT named subjects legitimately having different
// checksum values under the same key name is completely normal (that's
// what a lockfile is for) and must not be flagged as a mismatch.
func TestDetect_SameKeyDifferentSubjects_ProducesNoMatch(t *testing.T) {
	content := []byte(
		"[[package]]\n" +
			"name = \"pkg-a\"\n" +
			"checksum = \"" + sha256A + "\"\n" +
			"\n" +
			"[[package]]\n" +
			"name = \"pkg-b\"\n" +
			"checksum = \"" + sha256B + "\"\n",
	)

	d := detector{}
	matches := d.Detect("Cargo.lock.toml", content)

	if len(matches) != 0 {
		t.Fatalf("Detect() returned %d matches, want 0 for two distinct named subjects with distinct checksums; matches=%+v", len(matches), matches)
	}
}

// TestDetect_DirtyJSONLockfile_ProducesMatch covers the JSON "key": "value"
// syntax named alongside TOML in the pattern description (*.lock.json), and
// a sha1 (40-hex-char)-shaped digest key instead of sha256, plus a
// "digest"-named key instead of "checksum" -- exercising the broader
// checksum/digest/hash/sha key-name vocabulary the description lists.
func TestDetect_DirtyJSONLockfile_ProducesMatch(t *testing.T) {
	content := []byte(
		"{\n" +
			"  \"lockfileVersion\": 3,\n" +
			"  \"packages\": [\n" +
			"    {\n" +
			"      \"name\": \"pkg\",\n" +
			"      \"resolved\": \"https://registry.example/pkg-1.0.0.tgz\",\n" +
			"      \"digest\": \"" + sha1A + "\"\n" +
			"    },\n" +
			"    {\n" +
			"      \"name\": \"pkg\",\n" +
			"      \"resolved\": \"https://registry.example/pkg-1.0.0.tgz\",\n" +
			"      \"digest\": \"" + sha1B + "\"\n" +
			"    }\n" +
			"  ]\n" +
			"}\n",
	)

	d := detector{}
	matches := d.Detect("package.lock.json", content)

	if len(matches) != 1 {
		t.Fatalf("Detect() returned %d matches, want exactly 1 for a same-subject digest mismatch; matches=%+v", len(matches), matches)
	}
	// Line 12 is the second "digest": ... line.
	assertMatch(t, matches[0], 12)
}

// TestDetect_NonHexShapedValues_ProducesNoMatch covers files that use a
// checksum-named key but whose value is not a bare 40/64-hex-char string
// (e.g. an algorithm-prefixed digest like "sha256-abcd...", or a value of
// the wrong length) -- these should never match, since the pattern
// description is specific about the exact hex lengths it extracts.
func TestDetect_NonHexShapedValues_ProducesNoMatch(t *testing.T) {
	content := []byte(
		"name = \"pkg\"\n" +
			"checksum = \"sha256-not-a-bare-hex-digest\"\n" +
			"\n" +
			"[[package]]\n" +
			"name = \"pkg\"\n" +
			"checksum = \"deadbeef\"\n",
	)

	d := detector{}
	matches := d.Detect("Cargo.lock.toml", content)

	if len(matches) != 0 {
		t.Fatalf("Detect() returned %d matches, want 0 when no value is a bare 40/64-hex-char string; matches=%+v", len(matches), matches)
	}
}

// TestDetect_EmptyContent_ProducesNoMatch is a basic degenerate-input check.
func TestDetect_EmptyContent_ProducesNoMatch(t *testing.T) {
	d := detector{}
	matches := d.Detect("Cargo.lock.toml", []byte{})

	if len(matches) != 0 {
		t.Fatalf("Detect() returned %d matches for empty content, want 0", len(matches))
	}
}

func TestID(t *testing.T) {
	d := detector{}
	if got := d.ID(); got != "lockfile-checksum-mismatch" {
		t.Errorf("ID() = %q, want %q", got, "lockfile-checksum-mismatch")
	}
}

func TestCategory(t *testing.T) {
	d := detector{}
	if got := d.Category(); got != "generated-artifact-tampering" {
		t.Errorf("Category() = %q, want %q", got, "generated-artifact-tampering")
	}
}
