// Copyright 2026 anti-cheat-scorecard Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package generatedbannermissingtoolref

import (
	"testing"

	"github.com/ossf/scorecard/v5/internal/llmcheat"
)

// TestDetect_UnlabeledAutoGeneratedBanner_ProducesMatch exercises the exact
// dirty shape from the task description, expanded into a realistic
// generated-looking Go file: an "AUTO-GENERATED FILE. DO NOT EDIT." banner
// that never says what produced the file.
func TestDetect_UnlabeledAutoGeneratedBanner_ProducesMatch(t *testing.T) {
	content := []byte(`// AUTO-GENERATED FILE. DO NOT EDIT.

package widgetpb

type Widget struct {
	Name string
	ID   int64
}
`)

	d := detector{}
	matches := d.Detect("pkg/widgetpb/widget.pb.go", content)

	if len(matches) < 1 {
		t.Fatalf("Detect() returned %d matches, want at least 1 for an unlabeled AUTO-GENERATED banner", len(matches))
	}
	for _, m := range matches {
		if m.PatternID != "generated-banner-missing-tool-reference" {
			t.Errorf("Match.PatternID = %q, want %q", m.PatternID, "generated-banner-missing-tool-reference")
		}
		if m.Category != "generated-artifact-tampering" {
			t.Errorf("Match.Category = %q, want %q", m.Category, "generated-artifact-tampering")
		}
	}
	if matches[0].Line != 1 {
		t.Errorf("Match.Line = %d, want 1 (the banner line)", matches[0].Line)
	}
}

// TestDetect_ProtocBannerWithByClause_ProducesNoMatches proves the exact
// clean shape from the task description -- a real protoc-gen-go-grpc
// banner that names its tool via "by" -- produces zero matches.
func TestDetect_ProtocBannerWithByClause_ProducesNoMatches(t *testing.T) {
	content := []byte(`// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// source: widget.proto

package widgetpb
`)

	d := detector{}
	matches := d.Detect("pkg/widgetpb/widget_grpc.pb.go", content)

	if len(matches) != 0 {
		t.Fatalf("Detect() returned %d matches, want 0 for a properly-labeled protoc banner: %+v", len(matches), matches)
	}
}

// TestDetect_ViaClauseAllowlisted proves a banner that names its tool with
// "via" instead of "by" is also recognized as labeled.
func TestDetect_ViaClauseAllowlisted(t *testing.T) {
	content := []byte(`// @generated via ggen sync -- do not hand-edit.

package ontology
`)

	d := detector{}
	matches := d.Detect("internal/ontology/generated.go", content)

	if len(matches) != 0 {
		t.Fatalf("Detect() returned %d matches, want 0 for a banner naming its tool with \"via\": %+v", len(matches), matches)
	}
}

// TestDetect_BacktickedRegenerateCommandAllowlisted proves a banner that
// names no "by"/"via" tool but does give a backticked regenerate command is
// still treated as labeled: the command itself is the tool reference.
func TestDetect_BacktickedRegenerateCommandAllowlisted(t *testing.T) {
	content := []byte(`// This file was auto-generated. To regenerate, run ` + "`make generate`" + `.

package api
`)

	d := detector{}
	matches := d.Detect("internal/api/generated.go", content)

	if len(matches) != 0 {
		t.Fatalf("Detect() returned %d matches, want 0 for a banner with a backticked regenerate command: %+v", len(matches), matches)
	}
}

// TestDetect_BareKnownToolNameAllowlisted proves a banner that names a
// recognizable generator token (no "by"/"via"/backtick needed) is treated
// as labeled -- covering the "known-tool-looking token like
// protoc/mockgen/sqlc/ggen/codegen" branch of the description directly.
func TestDetect_BareKnownToolNameAllowlisted(t *testing.T) {
	tests := []struct {
		name    string
		content string
	}{
		{"ggen", "// @generated ggen v1.2.0\n\npackage ontology\n"},
		{"sqlc", "// Code generated by sqlc. DO NOT EDIT.\n\npackage db\n"},
		{"mockgen", "// AUTO-GENERATED via mockgen -source=widget.go\n\npackage mocks\n"},
	}

	d := detector{}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			matches := d.Detect("generated.go", []byte(tt.content))
			if len(matches) != 0 {
				t.Errorf("Detect() returned %d matches for a %s-labeled banner, want 0: %+v", len(matches), tt.name, matches)
			}
		})
	}
}

// TestDetect_BannerOutsideFirstFiveLines_ProducesNoMatches proves the
// pattern respects its own stated scope: a generated-file claim that first
// appears after line 5 (e.g. buried under a long license header) is out of
// the banner window entirely and is not flagged.
func TestDetect_BannerOutsideFirstFiveLines_ProducesNoMatches(t *testing.T) {
	content := []byte(`// Copyright 2026 Example Corp.
//
// Licensed under the Apache License, Version 2.0.
// See LICENSE for details.
// Additional header padding line.
// AUTO-GENERATED FILE. DO NOT EDIT.

package widget
`)

	d := detector{}
	matches := d.Detect("pkg/widget/widget.go", content)

	if len(matches) != 0 {
		t.Fatalf("Detect() returned %d matches, want 0 for a banner starting at line 6 (outside the first %d lines): %+v",
			len(matches), maxBannerLines, matches)
	}
}

// TestDetect_NoGeneratedClaim_ProducesNoMatches proves ordinary
// hand-written source with no generated-file claim at all is never
// flagged.
func TestDetect_NoGeneratedClaim_ProducesNoMatches(t *testing.T) {
	content := []byte(`// Package widget implements the widget domain type.
package widget

// Widget is a named, identified widget.
type Widget struct {
	Name string
	ID   int64
}
`)

	d := detector{}
	matches := d.Detect("pkg/widget/widget.go", content)

	if len(matches) != 0 {
		t.Fatalf("Detect() returned %d matches, want 0 for hand-written source with no generated banner: %+v", len(matches), matches)
	}
}

// TestDetect_ImplementsPatternInterface is a compile-time-flavored check
// that detector really satisfies llmcheat.Pattern and reports the expected
// ID/Category via the real interface methods (not just the concrete type).
func TestDetect_ImplementsPatternInterface(t *testing.T) {
	var p llmcheat.Pattern = detector{}
	if p.ID() != "generated-banner-missing-tool-reference" {
		t.Errorf("ID() = %q, want %q", p.ID(), "generated-banner-missing-tool-reference")
	}
	if p.Category() != "generated-artifact-tampering" {
		t.Errorf("Category() = %q, want %q", p.Category(), "generated-artifact-tampering")
	}
}
