// Copyright 2026 anti-cheat-scorecard Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Package generatedbannermissingtoolref implements the
// "generated-banner-missing-tool-reference" llmcheat.Pattern: it flags a
// "Code generated" / "@generated" / "AUTO-GENERATED" style banner living in
// a file's first few lines that does NOT name the actual generator/tool/
// command that produced the file anywhere in that same banner block.
//
// Legitimate generated-file banners (Go's own "Code generated by <tool>. DO
// NOT EDIT." convention at https://go.dev/s/generatedcode, protoc/buf/sqlc/
// mockgen/etc. headers) always tie the claim to a concrete, re-runnable
// generation step: "by <tool>", "via <tool>", a backticked regenerate
// command, or the tool's own name. A banner that merely asserts
// "AUTO-GENERATED. DO NOT EDIT." with no such reference is an unverifiable
// claim -- there is no way to confirm the file was actually produced by a
// deterministic tool rather than hand- or LLM-written and dressed up to
// look generated (which also makes it look exempt from human review).
package generatedbannermissingtoolref

import (
	"bufio"
	"bytes"
	"fmt"
	"regexp"
	"strings"

	"github.com/ossf/scorecard/v5/internal/llmcheat"
)

const (
	patternID = "generated-banner-missing-tool-reference"
	category  = "generated-artifact-tampering"

	// maxBannerLines bounds how many leading lines of a file are treated as
	// its "generated" banner block, per the pattern's own scope: a
	// generated-file claim is only in scope when it appears near the very
	// top of the file, the way every real generated-code convention places
	// it.
	maxBannerLines = 5
)

var (
	// bannerTriggerRe matches the conventional phrasings that claim a file
	// is machine-generated: Go's "Code generated ... DO NOT EDIT."
	// convention, the "@generated" tag used by many non-Go generators
	// (Facebook/Meta tooling, some JS/TS codegen), and the generic
	// "AUTO-GENERATED" / "automatically generated" banner shape used
	// elsewhere.
	bannerTriggerRe = regexp.MustCompile(`(?i)(code\s+generated|@generated|auto[-\s]?generated|automatically\s+generated)`)

	// byWordRe / viaWordRe match a standalone "by"/"via" token (word
	// boundaries so substrings like "byte" or "obviously" never falsely
	// count as naming a tool).
	byWordRe  = regexp.MustCompile(`(?i)\bby\b`)
	viaWordRe = regexp.MustCompile(`(?i)\bvia\b`)

	// backtickCommandRe matches a backtick-quoted command/tool reference,
	// e.g. "regenerate with `buf generate`" or "run `make generate`".
	backtickCommandRe = regexp.MustCompile("`[^`\n]+`")

	// knownToolRe matches common code-generator tool/command names that by
	// themselves name the generator even without an accompanying
	// "by"/"via"/backtick, e.g. a banner that just states
	// "protoc-gen-go-grpc v1.3.0" or "ggen sync" on its own line.
	knownToolRe = regexp.MustCompile(`(?i)\b(protoc(?:-gen-[a-z0-9-]+)?|mockgen|sqlc|ggen|codegen|stringer|swagger|openapi-generator|oapi-codegen|thrift|buf|wire|gqlgen|antlr|goyacc|yacc|deepcopy-gen|client-gen|informer-gen|lister-gen|conversion-gen|defaulter-gen|go-bindata|packr|mockery|easyjson|ffjson|go\s+generate)\b`)
)

// detector is the real, stateless implementation of llmcheat.Pattern for
// this pattern. It has no fields because Detect is a pure function of its
// arguments; it exists as a named type only so it can implement the
// interface and be registered.
type detector struct{}

func init() {
	llmcheat.Register(detector{})
}

func (detector) ID() string       { return patternID }
func (detector) Category() string { return category }

// Detect reads the first maxBannerLines lines of content. If any of those
// lines contains a "generated" claim (bannerTriggerRe) but none of the
// lines in that same window names the actual generator/tool/command that
// produced the file -- via "by", "via", a backticked command, or a
// recognizable tool name -- it reports one Match anchored at the first
// triggering line.
func (d detector) Detect(path string, content []byte) []llmcheat.Match {
	lines := firstLines(content, maxBannerLines)
	if len(lines) == 0 {
		return nil
	}

	var triggerLine uint
	var triggerText string
	for i, line := range lines {
		if bannerTriggerRe.MatchString(line) {
			triggerLine = uint(i + 1)
			triggerText = strings.TrimSpace(line)
			break
		}
	}
	if triggerLine == 0 {
		// No generated-file claim in the banner window at all -- nothing
		// for this pattern to evaluate.
		return nil
	}

	block := strings.Join(lines, "\n")
	if hasToolReference(block) {
		return nil
	}

	return []llmcheat.Match{{
		PatternID: patternID,
		Category:  category,
		Path:      path,
		Line:      triggerLine,
		Message: fmt.Sprintf(
			"generated-file banner %q (line %d) claims the file is machine-generated but names no generator/tool/command "+
				"(no \"by\", \"via\", backticked command, or recognizable tool name) anywhere in the first %d lines",
			triggerText, triggerLine, maxBannerLines),
		Severity: llmcheat.SeverityMedium,
	}}
}

// hasToolReference reports whether block -- the joined text of the banner
// window -- names an actual generator/tool/command anywhere in it.
func hasToolReference(block string) bool {
	return byWordRe.MatchString(block) ||
		viaWordRe.MatchString(block) ||
		backtickCommandRe.MatchString(block) ||
		knownToolRe.MatchString(block)
}

// firstLines returns up to n leading lines of content, split on newlines,
// with any trailing carriage return trimmed so CRLF-terminated files are
// handled the same as LF-terminated ones.
func firstLines(content []byte, n int) []string {
	var lines []string
	scanner := bufio.NewScanner(bytes.NewReader(content))
	scanner.Buffer(make([]byte, 0, 64*1024), 1024*1024)
	for scanner.Scan() && len(lines) < n {
		lines = append(lines, strings.TrimRight(scanner.Text(), "\r"))
	}
	return lines
}
