// Copyright 2026 anti-cheat-scorecard Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Package generatedfilemanualfixcomment implements the
// "generated-file-manual-fix-comment" llmcheat Pattern: it flags a file that
// declares itself machine-generated ("generated by", "@generated",
// "DO NOT EDIT", "DO NOT MODIFY") and ALSO contains, somewhere in the same
// file, prose that admits a human patched it anyway ("manually patched",
// "hand-fixed", "workaround added manually", "temporary manual override").
//
// This is the same detection family as handeditedgeneratedfilemarker (a
// generated-file declaration plus a same-file admission of hand-editing is
// the signal, neither half alone is suspicious) but keyed on full prose
// phrases rather than code-comment sigils like "// HACK" or "// FIXME by".
// That difference in vocabulary matters: sigils only ever show up inside a
// source-code comment syntax, so a pattern built around them is blind to a
// README changelog entry, a YAML manifest's trailing comment, or a JSON
// config's "_comment" field that documents the exact same tampering in
// ordinary sentences. Detect therefore runs on any text content it is given,
// with no file-extension restriction and no restriction to a leading header
// window — the generated-file declaration and the manual-fix admission can
// each appear anywhere in the file (a changelog note near the bottom of a
// generated Markdown doc is just as real a signal as one in the first line).
package generatedfilemanualfixcomment

import (
	"bufio"
	"bytes"
	"fmt"
	"strings"

	"github.com/ossf/scorecard/v5/internal/llmcheat"
)

const (
	patternID       = "generated-file-manual-fix-comment"
	patternCategory = "generated-artifact-tampering"
)

// generatedMarkers are the literal phrases that identify a file as
// machine-generated. Matched case-insensitively against the whole file,
// since real-world generator banners vary casing ("DO NOT MODIFY" vs
// "Do Not Modify" vs a lowercase "@generated" convention) but the phrases
// themselves are fixed, per this pattern's specification.
var generatedMarkers = []string{
	"generated by",
	"@generated",
	"do not edit",
	"do not modify",
}

// manualFixMarkers are the literal phrases that admit a human patched a file
// after it was generated. Matched case-insensitively for the same reason as
// generatedMarkers: prose capitalization is not a reliable signal either way
// ("Manually patched" at the start of a changelog bullet is just as real an
// admission as "manually patched" mid-sentence).
var manualFixMarkers = []string{
	"manually patched",
	"hand-fixed",
	"workaround added manually",
	"temporary manual override",
}

// detector is the real, stateless implementation of llmcheat.Pattern for
// this pattern. It holds no fields because Detect is a pure function of its
// arguments: the type exists only to give the interface methods a receiver.
type detector struct{}

func (detector) ID() string { return patternID }

func (detector) Category() string { return patternCategory }

// Detect scans content for the generated-marker + manual-fix-admission
// combination described in the package doc. It first checks whether ANY line
// in the file declares the file generated; if not, it returns immediately
// with no matches (a "manually patched" note in an ordinary, non-generated
// file — e.g. a runbook describing a manual production fix — is not this
// pattern's concern; that admission is expected and honest there). Only once
// that whole-file check passes does it scan every line for a manual-fix
// admission, producing one Match per line that contains one, with a real
// 1-based line number computed from an actual running counter over the
// scanned lines.
func (detector) Detect(path string, content []byte) []llmcheat.Match {
	lines := splitLines(content)
	if len(lines) == 0 {
		return nil
	}

	if !anyLineContainsMarker(lines, generatedMarkers) {
		return nil
	}

	var matches []llmcheat.Match
	for i, line := range lines {
		marker, found := findMarker(line, manualFixMarkers)
		if !found {
			continue
		}
		matches = append(matches, llmcheat.Match{
			PatternID: patternID,
			Category:  patternCategory,
			Path:      path,
			Line:      uint(i + 1),
			Message: fmt.Sprintf(
				"file declares itself machine-generated (a %q-style marker appears elsewhere in the file) but also documents the manual-fix admission %q, meaning a regeneratable artifact was hand-patched and the real source of truth has silently drifted: %s",
				"DO NOT EDIT", marker, strings.TrimSpace(line),
			),
			Severity: llmcheat.SeverityHigh,
		})
	}

	return matches
}

// splitLines splits content into its constituent lines using a real
// line-oriented scan (not a naive strings.Split on "\n", which mishandles a
// trailing-newline-less final line inconsistently across callers). The
// scanner's buffer is raised well above bufio's 64KiB default so one
// unusually long generated line (a minified table, a long import list)
// doesn't cause a silent bufio.ErrTooLong scan failure that would make this
// detector miss real matches.
func splitLines(content []byte) []string {
	if len(content) == 0 {
		return nil
	}
	var lines []string
	scanner := bufio.NewScanner(bytes.NewReader(content))
	scanner.Buffer(make([]byte, 0, 64*1024), 1024*1024)
	for scanner.Scan() {
		lines = append(lines, scanner.Text())
	}
	return lines
}

// anyLineContainsMarker reports whether any of lines contains,
// case-insensitively, any entry of markers.
func anyLineContainsMarker(lines []string, markers []string) bool {
	for _, line := range lines {
		lower := strings.ToLower(line)
		for _, marker := range markers {
			if strings.Contains(lower, marker) {
				return true
			}
		}
	}
	return false
}

// findMarker reports the first markers entry contained in line,
// case-insensitively, if any. The returned marker is the canonical
// lowercase phrase from markers (not the raw substring from line), so
// callers get a stable, spec-matching identifier for the Message field
// regardless of how the source text capitalized it.
func findMarker(line string, markers []string) (marker string, found bool) {
	lower := strings.ToLower(line)
	for _, marker := range markers {
		if strings.Contains(lower, marker) {
			return marker, true
		}
	}
	return "", false
}

func init() {
	llmcheat.Register(detector{})
}
