// Copyright 2026 anti-cheat-scorecard Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package generatedfilemanualfixcomment

import (
	"strings"
	"testing"

	"github.com/ossf/scorecard/v5/internal/llmcheat"
)

// dirtyYAMLConfig is a realistic generated Kubernetes ConfigMap manifest
// whose header declares it must never be touched, and whose body admits, in
// a trailing YAML comment, that someone patched a value by hand during an
// outage anyway.
const dirtyYAMLConfig = `# Code generated by scripts/gen_config.py. DO NOT MODIFY THIS FILE.
# Environment: production
apiVersion: v1
kind: ConfigMap
metadata:
  name: feature-flags
data:
  # temporary manual override applied 2026-01-01 to unblock the outage
  rollout_percentage: "100"
  # everything below regenerates cleanly on the next run
  legacy_mode: "false"
`

// cleanYAMLConfig is the same generated manifest with no manual-fix
// admission anywhere — a legitimate, untouched generated artifact.
const cleanYAMLConfig = `# DO NOT MODIFY THIS FILE. Generated by scripts/gen_config.py.
# Environment: production
apiVersion: v1
kind: ConfigMap
metadata:
  name: feature-flags
data:
  rollout_percentage: "50"
  legacy_mode: "false"
`

func TestDetect_DirtyGeneratedConfigWithManualOverride_ProducesMatch(t *testing.T) {
	d := detector{}

	matches := d.Detect("config/feature-flags.yaml", []byte(dirtyYAMLConfig))

	if len(matches) < 1 {
		t.Fatalf("Detect() on dirty fixture = %d matches, want >= 1", len(matches))
	}

	got := matches[0]
	if got.PatternID != patternID {
		t.Errorf("Match.PatternID = %q, want %q", got.PatternID, patternID)
	}
	if got.Category != patternCategory {
		t.Errorf("Match.Category = %q, want %q", got.Category, patternCategory)
	}
	if got.Path != "config/feature-flags.yaml" {
		t.Errorf("Match.Path = %q, want %q", got.Path, "config/feature-flags.yaml")
	}

	// Derive the expected 1-based line number directly from the fixture
	// text itself (rather than a hand-counted literal, which is easy to get
	// off-by-one on a multi-line raw string) so the assertion stays correct
	// even if the fixture is edited later.
	wantLine := uint(0)
	for i, line := range strings.Split(dirtyYAMLConfig, "\n") {
		if strings.Contains(line, "temporary manual override") {
			wantLine = uint(i + 1)
			break
		}
	}
	if wantLine == 0 {
		t.Fatal("test fixture bug: dirtyYAMLConfig does not contain the expected marker")
	}
	if got.Line != wantLine {
		t.Errorf("Match.Line = %d, want %d", got.Line, wantLine)
	}
	if got.Severity != llmcheat.SeverityHigh {
		t.Errorf("Match.Severity = %q, want %q", got.Severity, llmcheat.SeverityHigh)
	}
	if got.Message == "" {
		t.Error("Match.Message is empty, want a real explanation")
	}
}

func TestDetect_CleanGeneratedConfig_ProducesNoMatches(t *testing.T) {
	d := detector{}

	matches := d.Detect("config/feature-flags.yaml", []byte(cleanYAMLConfig))

	if len(matches) != 0 {
		t.Fatalf("Detect() on clean fixture = %d matches, want 0; matches=%+v", len(matches), matches)
	}
}

// TestDetect_ManualFixAdmissionWithoutGeneratedMarker_ProducesNoMatches
// proves the combination requirement: an ordinary, non-generated runbook
// that legitimately documents a manual production fix (a completely honest,
// expected thing for a hand-authored operational doc to say) must not be
// flagged. The generated-file declaration is the other half of the signal,
// and it is absent here.
func TestDetect_ManualFixAdmissionWithoutGeneratedMarker_ProducesNoMatches(t *testing.T) {
	const src = `# Incident Runbook: Feature Flag Rollback

During the 2026-01-01 outage, the on-call engineer applied a temporary
manual override to the rollout percentage directly in the running
cluster to stop the bleeding, then filed a follow-up ticket to make it
permanent through the normal config pipeline.
`
	d := detector{}

	matches := d.Detect("docs/runbooks/rollback.md", []byte(src))

	if len(matches) != 0 {
		t.Fatalf("Detect() on non-generated fixture = %d matches, want 0; matches=%+v", len(matches), matches)
	}
}

// TestDetect_ManualFixMarkerAtEndOfLongMarkdownDoc_ProducesMatch proves the
// pattern is not scoped to a leading header window: the generated-file
// declaration sits on line 1 of a Markdown changelog, and the admission of a
// hand-fix appears many lines later, near the bottom, exactly the kind of
// trailing changelog note a code-comment-sigil-only pattern would miss.
func TestDetect_ManualFixMarkerAtEndOfLongMarkdownDoc_ProducesMatch(t *testing.T) {
	const src = `<!-- @generated by scripts/render_changelog.py -->
# Changelog

## v2.3.0
- Added support for nested profiles.
- Fixed a race condition in the sync loop.

## v2.2.1
- Patch release.

## v2.2.0
- Initial multi-tenant support.
- NOTE: entry above was hand-fixed after the generator mis-rendered the
  version heading; regenerate from source once the template bug is closed.
`
	d := detector{}

	matches := d.Detect("CHANGELOG.md", []byte(src))

	if len(matches) != 1 {
		t.Fatalf("Detect() on trailing-admission fixture = %d matches, want 1; matches=%+v", len(matches), matches)
	}
	got := matches[0]
	if got.PatternID != patternID {
		t.Errorf("Match.PatternID = %q, want %q", got.PatternID, patternID)
	}
	if got.Category != patternCategory {
		t.Errorf("Match.Category = %q, want %q", got.Category, patternCategory)
	}
	wantLine := uint(0)
	for i, line := range strings.Split(src, "\n") {
		if strings.Contains(line, "hand-fixed") {
			wantLine = uint(i + 1)
			break
		}
	}
	if got.Line != wantLine {
		t.Errorf("Match.Line = %d, want %d", got.Line, wantLine)
	}
}

// TestDetect_MultipleManualFixAdmissions_ProducesOneMatchPerLine proves that
// every distinct manual-fix-admission line in a generated file is reported,
// not just the first one found.
func TestDetect_MultipleManualFixAdmissions_ProducesOneMatchPerLine(t *testing.T) {
	const src = `// Code generated by templater. DO NOT EDIT.
package widgets

// workaround added manually because the codegen template omitted validation
func Validate(w Widget) error {
	if w.ID == "" {
		return errInvalidID
	}
	// this whole block was manually patched on 2026-02-14, see INC-4821
	return nil
}
`
	d := detector{}

	matches := d.Detect("gen/widgets/validate.go", []byte(src))

	if len(matches) != 2 {
		t.Fatalf("Detect() on multi-marker fixture = %d matches, want 2; matches=%+v", len(matches), matches)
	}
	if matches[0].Line != 4 {
		t.Errorf("matches[0].Line = %d, want 4", matches[0].Line)
	}
	if matches[1].Line != 9 {
		t.Errorf("matches[1].Line = %d, want 9", matches[1].Line)
	}
	for _, m := range matches {
		if m.PatternID != patternID {
			t.Errorf("Match.PatternID = %q, want %q", m.PatternID, patternID)
		}
		if m.Category != patternCategory {
			t.Errorf("Match.Category = %q, want %q", m.Category, patternCategory)
		}
	}
}

// TestDetect_EmptyContent_ProducesNoMatches guards the zero-value input
// edge case: empty file content must never panic or fabricate a match.
func TestDetect_EmptyContent_ProducesNoMatches(t *testing.T) {
	d := detector{}

	matches := d.Detect("empty.yaml", []byte(""))

	if len(matches) != 0 {
		t.Fatalf("Detect() on empty content = %d matches, want 0; matches=%+v", len(matches), matches)
	}
}

func TestPattern_IDAndCategory(t *testing.T) {
	d := detector{}

	if got := d.ID(); got != patternID {
		t.Errorf("ID() = %q, want %q", got, patternID)
	}
	if got := d.Category(); got != patternCategory {
		t.Errorf("Category() = %q, want %q", got, patternCategory)
	}
	if got := d.ID(); got != "generated-file-manual-fix-comment" {
		t.Errorf("ID() = %q, want the literal spec ID %q", got, "generated-file-manual-fix-comment")
	}
	if got := d.Category(); got != "generated-artifact-tampering" {
		t.Errorf("Category() = %q, want the literal spec Category %q", got, "generated-artifact-tampering")
	}
}
